# -*- coding: utf-8 -*-
"""credit_card_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hQvIFEwUn0-09hrl0r__HoJCMPghoZH
"""

import zipfile

with zipfile.ZipFile('/content/fraudTest.csv.zip', 'r') as z:
    z.extractall('/mnt/data')

with zipfile.ZipFile('/content/fraudTrain.csv.zip', 'r') as z:
    z.extractall('/mnt/data')

!pip install imbalanced-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

train = pd.read_csv('/mnt/data/fraudTrain.csv')
test  = pd.read_csv('/mnt/data/fraudTest.csv')

X = train.drop('is_fraud', axis=1)
y = train['is_fraud']

# Remove non-numeric columns
X = X.select_dtypes(include=['int64','float64'])

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))