# -*- coding: utf-8 -*-
"""customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kzlXXSQ1MGK4iGWBBnh2G5Ax-jqBCHA
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

y_train.isna().sum()

data = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

data['Churn'] = data['Churn'].replace({'Yes': 1, 'No': 0})

data.dropna(inplace=True)

data.drop('customerID', axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder
for col in data.select_dtypes(include='object'):
    data[col] = LabelEncoder().fit_transform(data[col])

X = data.drop('Churn', axis=1)
y = data['Churn']

y.isna().sum()   # MUST be 0

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

y_train.isna().sum()   # MUST be 0

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

sample = X_test.iloc[0:1]
sample
prediction = lr.predict(sample)
prediction
if prediction[0] == 1:
    print("Customer will CHURN ❌")
else:
    print("Customer will STAY ✅")